name: Anaconda Build

on: [push, pull_request]

jobs:

  analyze:
    name: analyze / python-${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-dev
          auto-update-conda: true
          environment-file: conda/environment-dev.yml
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Show environment variables
        shell: bash -l {0}
        run: |
          env | sort
      - name: Check style against standards using prospector
        shell: bash -l {0}
        run: prospector -o grouped -o pylint:pylint-report.txt
      - name: Check whether import statements are used consistently
        shell: bash -l {0}
        run: isort --check-only --diff --conda-env matchms-dev --recursive --lines-after-imports 2 --force-single-line --no-lines-before FUTURE --no-lines-before STDLIB --no-lines-before THIRDPARTY --no-lines-before FIRSTPARTY --no-lines-before LOCALFOLDER matchms/ tests/ integration-tests/
      - name: Build & test documentation
        shell: bash -l {0}
        run: |
          make coverage doctest html
        working-directory: readthedocs/
        env:
          SPHINXOPTS: "-n"  # enable nit-picky mode
      - name: Check documentation coverage threshold
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          cat readthedocs/_build/coverage/python.txt
          UNCOVERED_MEMBERS=$(grep '*' readthedocs/_build/coverage/python.txt | wc -l)
          UNCOVERED_MEMBERS_ALLOWED=25
          if (( $UNCOVERED_MEMBERS > $UNCOVERED_MEMBERS_ALLOWED )) ; then echo "There are currently ${UNCOVERED_MEMBERS} uncovered members in the documentation, which is more than the ${UNCOVERED_MEMBERS_ALLOWED} allowed."; exit 1;fi
          echo "The code is sufficiently documented with ${UNCOVERED_MEMBERS} uncovered members out of ${UNCOVERED_MEMBERS_ALLOWED} allowed.";
      - name: Test
        if: matrix.os != 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          python setup.py test
      - name: Test with coverage
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
      - name: Correct coverage paths
        if: matrix.os == 'ubuntu-latest'
        run: sed -i "s+$PWD/++g" coverage.xml
      - name: SonarCloud Scan
        if: matrix.os == 'ubuntu-latest'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: build / python-${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.7"]
    runs-on: ${{ matrix.os }}
    needs: analyze
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Create matchms-build environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-build
          auto-update-conda: true
          environment-file: conda/environment-build.yml
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda env list
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Show environment variables
        shell: bash -l {0}
        run: |
          env | sort
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          export BUILDDIR=$RUNNER_TEMP/matchms/_build
          [ "$RUNNING_OS" = "Windows" ] && export BUILDDIR=$RUNNER_TEMP\\matchms\\_build\\
          conda config --set anaconda_upload no
          conda build --numpy 1.18.1 --no-include-recipe \
            --channel bioconda --channel conda-forge \
            --croot ${BUILDDIR} \
            ./conda
      - name: Upload package artifact from build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: conda-package-artifact
          path: ${{ runner.temp }}/matchms/_build

  verify:
    name: verify / python-${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Create an environment to test the locally published package
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-test
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda env list
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Show environment variables
        shell: bash -l {0}
        run: |
          env | sort
      - name: Download conda package from build job
        uses: actions/download-artifact@v2
        with:
          name: conda-package-artifact
          path: ${{ runner.temp }}/matchms/_build
      - name: Artifact folder content
        shell: bash -l {0}
        run: |
          export BUILDDIR=$RUNNER_TEMP/matchms/_build/noarch/
          [ "$RUNNING_OS" = "Windows" ] && export BUILDDIR=$RUNNER_TEMP\\matchms\\_build\\noarch\\
          echo ${RUNNER_TEMP}/matchms/_build
      - name: List artifact folder content
        shell: bash -l {0}
        run: |
          export BUILDDIR=$RUNNER_TEMP/matchms/_build/noarch/
          [ "$RUNNING_OS" = "Windows" ] && export BUILDDIR=$RUNNER_TEMP\\matchms\\_build\\noarch\\
          ls -al ${RUNNER_TEMP}/matchms/_build
      - name: Test locally published conda package
        shell: bash -l {0}
        run: |
          export BUILDDIR=$RUNNER_TEMP/matchms/_build/noarch/
          [ "$RUNNING_OS" = "Windows" ] && export BUILDDIR=$RUNNER_TEMP\\matchms\\_build\\noarch\\
          conda install \
            --channel bioconda \
            --channel conda-forge \
            --channel $BUILDDIR \
            matchms
      - name: List conda packages
        shell: bash -l {0}
        run: |
          conda list
      - name: Install dev dependencies to run the tests
        shell: bash -l {0}
        run: |
          conda env update --name matchms-test --file conda/environment-dev.yml
          conda info
          conda list
      - name: Run tests after installing the package
        shell: bash -l {0}
        run: |
          export TESTDIR=$RUNNER_TEMP/matchms/_test
          [ "$RUNNING_OS" = "Windows" ] && export TESTDIR=$RUNNER_TEMP\\matchms\\_test\\
          mkdir $TESTDIR
          cp -iRv tests integration-tests $TESTDIR
          cd $TESTDIR
          pytest --ignore="tests/test_version_string_consistency.py"
